
SET SEARCH_PATH TO public, "$user","public";

SET SEARCH_PATH TO public, "$user","public";

SET SEARCH_PATH TO public, "$user","public";

-- Create Database Lock Table
CREATE TABLE public.databasechangeloglock (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (ID));

-- Initialize Database Lock Table
DELETE FROM public.databasechangeloglock;

INSERT INTO public.databasechangeloglock (ID, LOCKED) VALUES (1, FALSE);

-- Lock Database
UPDATE public.databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = 'archlinux (192.168.0.18)', LOCKGRANTED = NOW() WHERE ID = 1 AND LOCKED = FALSE;

SET SEARCH_PATH TO public, "$user","public";

-- Create Database Change Log Table
CREATE TABLE public.databasechangelog (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED TIMESTAMP WITHOUT TIME ZONE NOT NULL, ORDEREXECUTED INTEGER NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10));

SET SEARCH_PATH TO public, "$user","public";

SET SEARCH_PATH TO public, "$user","public";

-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: src/main/resources/db/changelog/db.changelog-master.yaml
-- Ran at: 29.07.2024, 17:44
-- Against: admin@jdbc:postgresql://localhost:5432/earsdb
-- Liquibase version: 4.24.0
-- *********************************************************************

SET SEARCH_PATH TO public, "$user","public";

SET SEARCH_PATH TO public, "$user","public";

-- Changeset src/main/resources/db/changelog/db.changelog-master.yaml::1::fizlrock
-- create users table
SET SEARCH_PATH TO public, "$user","public";

CREATE TABLE public.app_user (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(100) NOT NULL, CONSTRAINT app_user_pkey PRIMARY KEY (id), UNIQUE (username));

INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'fizlrock', 'src/main/resources/db/changelog/db.changelog-master.yaml', NOW(), 1, '9:02d79355f96e827a53dd142a46e51ad8', 'createTable tableName=app_user', 'create users table', 'EXECUTED', NULL, NULL, '4.24.0', NULL);

-- Changeset src/main/resources/db/changelog/db.changelog-master.yaml::2::fizlrock
-- Add password column
SET SEARCH_PATH TO public, "$user","public";

ALTER TABLE public.app_user ADD password_hash TEXT;

DELETE FROM public.app_user WHERE password_hash is null;

ALTER TABLE public.app_user ALTER COLUMN  password_hash SET NOT NULL;

INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('2', 'fizlrock', 'src/main/resources/db/changelog/db.changelog-master.yaml', NOW(), 2, '9:7a263e9135c0e882f9f94bc1b238de71', 'addColumn tableName=app_user; delete tableName=app_user; addNotNullConstraint columnName=password_hash, tableName=app_user', 'Add password column', 'EXECUTED', NULL, NULL, '4.24.0', NULL);

-- Changeset src/main/resources/db/changelog/db.changelog-master.yaml::3::fizlrock
-- create table for audio records info
SET SEARCH_PATH TO public, "$user","public";

CREATE TABLE public.audio_record_info (audio_info_id UUID NOT NULL, user_id BIGINT NOT NULL, durability BIGINT DEFAULT 0, record_date TIMESTAMP WITHOUT TIME ZONE, upload_date TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT audio_record_info_pkey PRIMARY KEY (audio_info_id), CONSTRAINT audio_record_info_user_fk FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE);

COMMENT ON COLUMN public.audio_record_info.user_id IS 'ID пользователя создавшего запись';

COMMENT ON COLUMN public.audio_record_info.durability IS 'Record durability in seconds';

COMMENT ON COLUMN public.audio_record_info.record_date IS 'the date and time when the recording was made';

COMMENT ON COLUMN public.audio_record_info.upload_date IS 'the date and time when the recording was uploaded';

INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('3', 'fizlrock', 'src/main/resources/db/changelog/db.changelog-master.yaml', NOW(), 3, '9:7ab18e00a9543edb3f0ff8a0c45527aa', 'createTable tableName=audio_record_info', 'create table for audio records info', 'EXECUTED', NULL, NULL, '4.24.0', NULL);

-- Changeset src/main/resources/db/changelog/db.changelog-master.yaml::4::fizlrock
-- add status column
SET SEARCH_PATH TO public, "$user","public";

ALTER TABLE public.audio_record_info ADD status VARCHAR(100);

INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('4', 'fizlrock', 'src/main/resources/db/changelog/db.changelog-master.yaml', NOW(), 4, '9:c74994ff365f25a0ecf7b35c0024778d', 'addColumn tableName=audio_record_info', 'add status column', 'EXECUTED', NULL, NULL, '4.24.0', NULL);

-- Release Database Lock
SET SEARCH_PATH TO public, "$user","public";

UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

SET SEARCH_PATH TO public, "$user","public";


